### ISSUE TITLE
括弧で囲まれた文章が一文として判定される

### ISSUE THREAD

**Issue by HBonsai** [textlint-ja/textlint-rule-max-ten#17]
![image](https://user-images.githubusercontent.com/10624619/157427894-7e633660-1ed2-455d-aeab-29876b56d4a8.png)

「」や各種括弧内の文章が"？　"で文を区切っているにもかかわらず一文として判定され、別々の文でも"、"を「」内で規定回数以上使っていると指摘対象になってしまいます。小説を書くときは文章を「」で囲うことは珍しくないため、囲っていても通常の文と同様に扱っていただけると助かります。

この問題は"！　"や"。"で区切った際には起こらないようです。他に発生条件がないかどうかは現在調査中です。

**Comment by azu** [comment]
https://github.com/textlint-ja/textlint-rule-max-ten/releases/tag/v4.0.4 で修正しました。

「...」の中で区切り文字が`。`だけになっていて、`？`などが区切り文字として扱われてなかったので、発生していたバグなのかなと思います。
