### ISSUE TITLE
「，．」を指定できるようにしたい

### ISSUE THREAD

**Issue by nrkt** [textlint-ja/textlint-rule-max-ten#7]
現状は「、。」のチェックのみとなっていますが、「，．」をチェックできるようになるととてもありがたいです！

**Comment by azu** [comment]
https://github.com/textlint-ja/textlint-rule-max-ten/blob/3dfb5f458d170079401c5a501553ce46c59eaa2b/src/max-ten.js#L51
https://github.com/textlint-ja/textlint-rule-max-ten/blob/3dfb5f458d170079401c5a501553ce46c59eaa2b/src/max-ten.js#L75
https://github.com/textlint-ja/textlint-rule-max-ten/blob/3dfb5f458d170079401c5a501553ce46c59eaa2b/src/max-ten.js#L89
https://github.com/textlint-ja/textlint-rule-max-ten/blob/3dfb5f458d170079401c5a501553ce46c59eaa2b/src/max-ten.js#L97
この辺でハードコードされている部分をオプションとして渡せるようになれば、対応できそうな気がしますね。

次のようなイメージのオプションがあるとよさそうなのかな。
`,` と `。` の組み合わせ をサポートするなら個別指定でよさそうな気がしますが、こういう書き方をするパターンはあるのかな。

```json
{
  "rules": {
    "max-ten": {
        "max" : 3,
        "touten": ",",
        "kuten": "。",
    }
  }
}
```

**Comment by nrkt** [comment]
迅速な対応ありがとうございます！
返信が遅くなり申し訳ありません。

上記のようなオプションがあるととてもありがたいです！
自分は「`、`と`。`」と「`，`と`．`」の組合せだけあればよいと思っていたのですが，他の組合せがないとは言い切れないので上記のようなオプションが良いのではないかと思いました。

**Comment by azu** [comment]
https://github.com/textlint-ja/textlint-rule-max-ten/releases/tag/v3.0.0 で実装しました。
```json5
{
  "rules": {
    "max-ten": {
      // 読点として扱う文字
      "touten": "，",
      // 句点として扱う文字
      "kuten": "．"
    }
  }
}
```
で利用できます。

**Comment by nrkt** [comment]
ありがとうございます！！
